include:
  - project: 'ExplorViz/code/deployment'
    file: '.gitlab-ci-explorviz-common.yml'

stages:
  - test
  - deploy:images
  - deploy:retagging

run-pre-commit:
  stage: test
  image: explorviz/pre-commit:latest
  tags:
    - exec-docker
  script:
    - pre-commit run --all-files --config pre-commit/.pre-commit-config.yaml

deploy-pre-commit-amd64:
  extends:
    - .build-and-deploy
  variables:
    DOCKER_CONTEXT_PATH: $CI_PROJECT_DIR/pre-commit
  rules:
    - if: $ARM64_BUILD
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"'

retag-pre-commit-amd64-as-latest:
  extends: .retag-dockerhub-image
  rules:
    - if: $MULTI_ARCH_BUILD || $ARM64_BUILD
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"'
  variables:
    SOURCE_TAG: 'amd64'
    TARGET_TAG: 'latest'
