repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master  # Use the ref you want to point at
    hooks:
      - id: check-yaml
        verbose: true
      - id: end-of-file-fixer
        verbose: true
      - id: trailing-whitespace
        verbose: true