repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master  # Use the ref you want to point at
    hooks:
      - id: check-yaml
        log_file: pre-commit.log
      - id: end-of-file-fixer
        log_file: pre-commit.log
      - id: trailing-whitespace
        log_file: pre-commit.log