#FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image@sha256:4a12f33a70dff6fa0949b4a5fe9c43ad08c4445a9120c10528a288ffc8481830

USER root
RUN microdnf install findutils

ENTRYPOINT [ "" ]
