FROM gitlab/gitlab-ce:16.10.1-ce.0

ENV GITLAB_ROOT_EMAIL=root@local
ENV GITLAB_ROOT_PASSWORD=hhn<hkbS1C@?FZC%0hIX

COPY 25_api_personal_access_token.rb opt/gitlab/embedded/service/gitlab-rails/db/fixtures/production/25_api_personal_access_token.rb